# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Client to GitHub Pages

on:
  push:
    branches: [ "gh-actions" ]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: cd client && npm ci
      - name: Build Client
        run: cd client && npm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifact_name: "github-pages"