name: Deploy Client to Firebase Hosting

on:
  push:
    branches: [ "main" ]

permissions:
  checks: write
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd client && npm ci
      - run: cd client && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAYANK_GUPTA_PORTFOLIO }}
          projectId: mayank-gupta-portfolio
