name: Deploy Client to Firebase Hosting

on:
  push:
    branches: [ "firebase" ]

permissions:
  checks: write
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: cd client && npm ci
      - name: Build Client
        run: cd client && npm run build
      - uses: lowply/deploy-firebase@v0.0.5
        with:
          entryPoint: client
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ env.FIREBASE_PROJECT }}